In [3]:
import pandas as pd
import numpy as np
from numpy.random import randn

In [16]:
my_df = pd.read_csv('csv_data/survey_results_public.csv')
my_df_schema = pd.read_csv('csv_data\survey_results_schema.csv',index_col='Column')

In [9]:
my_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88883 entries, 0 to 88882
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              88883 non-null  int64
 1   MainBranch              88331 non-null  object
 2   Hobbyist                88883 non-null  object
 3   OpenSourcer             88883 non-null  object
 4   OpenSource              86842 non-null  object
 5   Employment              87181 non-null  object
 6   Country                 88751 non-null  object
 7   Student                 87014 non-null  object
 8   EdLevel                 86390 non-null  object
 9   UndergradMajor          75614 non-null  object
 10  EduOther                84260 non-null  object
 11  OrgSize                 71791 non-null  object
 12  DevType                 81335 non-null  object
 13  YearsCode               87938 non-null  object
 14  Age1stCode              87634 non-null  object
 15  YearsCodePro            74331 non-null  object
 16  CareerSat               72847 non-null  object
 17  JobSat                  70988 non-null  object
 18  MgrIdiot                61159 non-null  object
 19  MgrMoney                61157 non-null  object
 20  MgrWant                 61232 non-null  object
 21  JobSeek                 80555 non-null  object
 22  LastHireDate            79854 non-null  object
 23  LastInt                 67155 non-null  object
 24  FizzBuzz                71344 non-null  object
 25  JobFactors              79371 non-null  object
 26  ResumeUpdate            77877 non-null  object
 27  CurrencySymbol          71392 non-null  object
 28  CurrencyDesc            71392 non-null  object
 29  CompTotal               55945 non-null  float64
 30  CompFreq                63268 non-null  object
 31  ConvertedComp           55823 non-null  float64
 32  WorkWeekHrs             64503 non-null  float64
 33  WorkPlan                68914 non-null  object
 34  WorkChallenge           68141 non-null  object
 35  WorkRemote              70284 non-null  object
 36  WorkLoc                 70055 non-null  object
 37  ImpSyn                  71779 non-null  object
 38  CodeRev                 70390 non-null  object
 39  CodeRevHrs              49790 non-null  float64
 40  UnitTests               62668 non-null  object
 41  PurchaseHow             61108 non-null  object
 42  PurchaseWhat            62029 non-null  object
 43  LanguageWorkedWith      87569 non-null  object
 44  LanguageDesireNextYear  84088 non-null  object
 45  DatabaseWorkedWith      76026 non-null  object
 46  DatabaseDesireNextYear  69147 non-null  object
 47  PlatformWorkedWith      80714 non-null  object
 48  PlatformDesireNextYear  77443 non-null  object
 49  WebFrameWorkedWith      65022 non-null  object
 50  WebFrameDesireNextYear  62944 non-null  object
 51  MiscTechWorkedWith      59586 non-null  object
 52  MiscTechDesireNextYear  64511 non-null  object
 53  DevEnviron              87317 non-null  object
 54  OpSys                   87851 non-null  object
 55  Containers              85366 non-null  object
 56  BlockchainOrg           48175 non-null  object
 57  BlockchainIs            60165 non-null  object
 58  BetterLife              86269 non-null  object
 59  ITperson                87141 non-null  object
 60  OffOn                   86663 non-null  object
 61  SocialMedia             84437 non-null  object
 62  Extraversion            87305 non-null  object
 63  ScreenName              80486 non-null  object
 64  SOVisit1st              83877 non-null  object
 65  SOVisitFreq             88263 non-null  object
 66  SOVisitTo               88086 non-null  object
 67  SOFindAnswer            87816 non-null  object
 68  SOTimeSaved             86344 non-null  object
 69  SOHowMuchTime           68378 non-null  object
 70  SOAccount               87828 non-null  object
 71  SOPartFreq              74692 non-null  object
 72  SOJobs                  88066 non-null  object
 73  EntTeams                87841 non-null  object
 74  SOComm                  88131 non-null  object
 75  WelcomeChange           85855 non-null  object
 76  SONewContent            69560 non-null  object
 77  Age                     79210 non-null  float64
 78  Gender                  85406 non-null  object
 79  Trans                   83607 non-null  object
 80  Sexuality               76147 non-null  object
 81  Ethnicity               76668 non-null  object
 82  Dependents              83059 non-null  object
 83  SurveyLength            86984 non-null  object
 84  SurveyEase              87081 non-null  object
dtypes: float64(5), int64(1), object(79)
memory usage: 57.6+ MB

In [10]:
my_df.shape

(88883, 85)

In [11]:
my_df.ndim   ##2dimension

2

In [20]:
my_df['OpenSourcer'].value_counts()

OpenSourcer
Never                                                 32295
Less than once per year                               24972
Less than once a month but more than once per year    20561
Once a month or more often                            11055
Name: count, dtype: int64

In [7]:
my_df.groupby('Country').size()

Country
Afghanistan                              44
Albania                                  86
Algeria                                 134
Andorra                                   7
Angola                                    5
                                       ...
Venezuela, Bolivarian Republic of...     88
Viet Nam                                231
Yemen                                    19
Zambia                                   12
Zimbabwe                                 39
Length: 179, dtype: int64

In [5]:
my_df.groupby('Country').count()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,44,42,44,44,41,38,36,39,27,38,...,40,33,23,30,27,21,23,30,41,39
Albania,86,85,86,86,84,86,77,81,76,77,...,80,76,72,83,80,78,72,77,83,83
Algeria,134,129,134,134,126,122,124,122,112,116,...,123,114,109,123,107,79,63,109,121,125
Andorra,7,7,7,7,7,7,6,7,1,6,...,7,5,4,5,5,6,5,5,6,6
Angola,5,5,5,5,5,5,4,3,3,4,...,4,3,3,4,4,4,4,3,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Venezuela, Bolivarian Republic of...",88,88,88,88,87,85,88,85,77,86,...,85,79,83,87,87,83,83,85,88,88
Viet Nam,231,227,231,231,224,218,221,224,165,199,...,225,198,173,211,205,141,152,204,221,219
Yemen,19,19,19,19,18,18,17,19,18,18,...,18,19,17,19,18,13,17,16,19,19
Zambia,12,12,12,12,11,12,12,12,11,12,...,12,12,11,12,11,12,11,12,12,12
Zimbabwe,39,39,39,39,38,38,39,38,29,37,...,39,36,35,39,36,37,38,38,39,38

In [25]:
my_df_short = my_df.iloc[0:10,0:5]
my_df_short

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro..."
5,6,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...
6,7,I am a developer by profession,No,Never,The quality of OSS and closed source software ...
7,8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro..."
8,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...
9,10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro..."

In [27]:
#get a count of all columns across all columns
my_df_short.apply(pd.value_counts)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource
1,1.0,NaN,NaN,NaN,NaN
2,1.0,NaN,NaN,NaN,NaN
3,1.0,NaN,NaN,NaN,NaN
4,1.0,NaN,NaN,NaN,NaN
5,1.0,NaN,NaN,NaN,NaN
6,1.0,NaN,NaN,NaN,NaN
7,1.0,NaN,NaN,NaN,NaN
8,1.0,NaN,NaN,NaN,NaN
9,1.0,NaN,NaN,NaN,NaN
10,1.0,NaN,NaN,NaN,NaN
I am a developer by profession,NaN,5.0,NaN,NaN,NaN
I am a student who is learning to code,NaN,2.0,NaN,NaN,NaN
"I am not primarily a developer, but I write code sometimes as part of my work",NaN,2.0,NaN,NaN,NaN
I code primarily as a hobby,NaN,1.0,NaN,NaN,NaN
Yes,NaN,NaN,7.0,NaN,NaN
No,NaN,NaN,3.0,NaN,NaN
Never,NaN,NaN,NaN,5.0,NaN
Once a month or more often,NaN,NaN,NaN,3.0,NaN
Less than once per year,NaN,NaN,NaN,2.0,NaN
The quality of OSS and closed source software is about the same,NaN,NaN,NaN,NaN,7.0
"OSS is, on average, of HIGHER quality than proprietary / closed source software",NaN,NaN,NaN,NaN,3.0

In [44]:
###my extra practice
my_df_short.groupby('Hobbyist').count()

          Respondent  MainBranch  OpenSourcer  OpenSource
Hobbyist
No                 3           3            3           3
Yes                7           7            7           7

In [46]:
##good usage
my_df_short.groupby(['Hobbyist'])['OpenSourcer'].value_counts()

Hobbyist  OpenSourcer
No        Never                         2
          Less than once per year       1
Yes       Never                         3
          Once a month or more often    3
          Less than once per year       1
Name: count, dtype: int64

In [47]:
###not so clear
my_df_short.groupby(['Hobbyist']).value_counts()

Hobbyist  Respondent  MainBranch                                                                     OpenSourcer                 OpenSource
No        2           I am a student who is learning to code                                         Less than once per year     The quality of OSS and closed source software is about the same                    1
          4           I am a developer by profession                                                 Never                       The quality of OSS and closed source software is about the same                    1
          7           I am a developer by profession                                                 Never                       The quality of OSS and closed source software is about the same                    1
Yes       1           I am a student who is learning to code                                         Never                       The quality of OSS and closed source software is about the same                    1
          3           I am not primarily a developer, but I write code sometimes as part of my work  Never                       The quality of OSS and closed source software is about the same                    1
          5           I am a developer by profession                                                 Once a month or more often  OSS is, on average, of HIGHER quality than proprietary / closed source software    1
          6           I am not primarily a developer, but I write code sometimes as part of my work  Never                       The quality of OSS and closed source software is about the same                    1
          8           I code primarily as a hobby                                                    Less than once per year     OSS is, on average, of HIGHER quality than proprietary / closed source software    1
          9           I am a developer by profession                                                 Once a month or more often  The quality of OSS and closed source software is about the same                    1
          10          I am a developer by profession                                                 Once a month or more often  OSS is, on average, of HIGHER quality than proprietary / closed source software    1
Name: count, dtype: int64

In [48]:
##good usage
my_df_short['OpenSourcer'].value_counts()

OpenSourcer
Never                         5
Once a month or more often    3
Less than once per year       2
Name: count, dtype: int64